# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (
    assetsbundle,
    avatar_mixin,
    decimal_precision,
    image_mixin,
    ir_actions,
    ir_actions_report,
    ir_asset,
    ir_attachment,
    ir_autovacuum,
    ir_config_parameter,
    ir_cron,
    ir_default,
    ir_demo,
    ir_demo_failure,
    ir_exports,
    ir_fields,
    ir_filters,
    ir_http,
    ir_logging,
    ir_mail_server,
    ir_model,
    ir_module,
    ir_profile,
    ir_property,
    ir_qweb,
    ir_qweb_fields,
    ir_rule,
    ir_sequence,
    ir_translation,
    ir_ui_menu,
    ir_ui_view,
    qweb,
    report_layout,
    report_paperformat,
    res_bank,
    res_company,
    res_config,
    res_country,
    res_currency,
    res_lang,
    res_partner,
    res_users,
)
