# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

from . import (
    assets,
    ir_actions,
    ir_asset,
    ir_attachment,
    ir_http,
    ir_model,
    ir_model_data,
    ir_module_module,
    ir_qweb,
    ir_qweb_fields,
    ir_rule,
    ir_translation,
    ir_ui_menu,
    ir_ui_view,
    mail_thread,
    mixins,
    res_company,
    res_config_settings,
    res_lang,
    res_partner,
    res_users,
    theme_models,
    website,
    website_configurator_feature,
    website_form,
    website_menu,
    website_page,
    website_rewrite,
    website_snippet_filter,
    website_visitor,
)
