# -*- coding: utf-8 -*-

from . import (
    test_access_rights,
    test_burndown_chart,
    test_multicompany,
    test_personal_stages,
    test_portal,
    test_project_base,
    test_project_config,
    test_project_flow,
    test_project_recurrence,
    test_project_sharing,
    test_project_sharing_portal_access,
    test_project_sharing_ui,
    test_project_subtasks,
    test_project_task_type,
    test_project_ui,
    test_project_update_access_rights,
    test_project_update_flow,
    test_project_update_ui,
    test_task_dependencies,
    test_task_follow,
    test_task_tracking,
)
