# -*- coding: utf-8 -*-

from . import (
    account_account,
    account_account_tag,
    account_analytic_default,
    account_analytic_line,
    account_bank_statement,
    account_cash_rounding,
    account_full_reconcile,
    account_incoterms,
    account_journal,
    account_journal_dashboard,
    account_move,
    account_move_line_tax_details,
    account_partial_reconcile,
    account_payment,
    account_payment_method,
    account_payment_term,
    account_reconcile_model,
    account_tax,
    account_tax_carryover_line,
    account_tax_report,
    chart_template,
    company,
    digest,
    ir_actions_report,
    ir_module_module,
    mail_thread,
    partner,
    product,
    res_bank,
    res_config_settings,
    res_currency,
    res_partner_bank,
    res_users,
    sequence_mixin,
)
