# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
from . import (
    test_attachment,
    test_auth_signup_uninvited,
    test_automatic_editor,
    test_base_url,
    test_configurator,
    test_controllers,
    test_converter,
    test_crawl,
    test_custom_snippets,
    test_disable_unused_snippets_assets,
    test_fuzzy,
    test_get_current_website,
    test_http_endpoint,
    test_ir_asset,
    test_lang_url,
    test_menu,
    test_page,
    test_performance,
    test_qweb,
    test_res_users,
    test_snippets,
    test_theme,
    test_ui,
    test_unsplash_beacon,
    test_views,
    test_views_inherit_module_update,
    test_website_favicon,
    test_website_form_editor,
    test_website_reset_password,
    test_website_visitor,
)
